(setq my-packages '(company
                    company-quickhelp
		    direx
		    drag-stuff
                    all-the-icons
		    expand-region
                    evil-leader
                    evil-nerd-commenter
                    evil-matchit
                    evil-visualstar
                    flx-ido
		    flyspell
                    flycheck
                    fancy-narrow
		    gitconfig-mode
		    gitignore-mode
		    grizzl
		    guide-key
		    helm
		    helm-descbinds
		    helm-gtags
		    helm-projectile
		    helm-swoop
                    helm-ag
                    helm-backup
		    ido-vertical-mode
		    json-mode
		    magit
		    multiple-cursors
		    org
		    org-bullets
                    ;; org-pomodoro
                    ;; org-drill
		    projectile
		    smart-mode-line
		    ;; smartparens
		    smex
		    undo-tree
		    use-package
                    which-key
		    yasnippet
		    zenburn-theme
                    ace-jump-buffer
                    ace-window
                    projectile
                    easy-kill
                    easy-kill-extras
                    zop-to-char
                    web-mode
                    csv-mode
                    ;;csv-nav
                    rainbow-delimiters
                    imenu-anywhere
                    aggressive-indent
                    iedit
                    ;;tidy
                    drag-stuff
                    elisp-slime-nav
                    better-defaults
                    color-identifiers-mode
                    whitespace-cleanup-mode
                    powerline
                    anzu
                    thingatpt
                    keyfreq
                    ag
                    swiper
                    counsel
                    super-save
                    smooth-scrolling
                    link-hint
                    highlight-parentheses
                    ;; neotree
                    quickrun
                    kurecolor
                    java-imports
                    origami
                    rainbow-mode
                    golden-ratio
                    golden-ratio-scroll-screen
                    popwin
                    git-timemachine
                    git-gutter-fringe+
                    git-gutter+
		    hydra
                    spaceline
                    restclient
                    restclient-helm
                    htmlize
                    window-numbering
                    highlight-numbers
                    hungry-delete
                    pbcopy
                    ctags-update
                    workgroups2
                    smartparens
                    clojure-mode
                    clojure-snippets
                    cider
                    ;;clojure-cheatsheet
                    cider-eval-sexp-fu
                    4clojure
                    paren-face
                    clj-refactor
                    ;;typed-clojure-mode
                    transpose-frame
                    auto-compile
                    sqlup-mode
                    sql-indent
                    peep-dired
                    ranger
                    xah-fly-keys
                    embrace
                    key-chord
                    mwim
                    worf
                    tiny
                    outshine
                    outorg
                    gitconfig-mode
                    gitignore-mode
                    gitattributes-mode
                    flyspell-correct-ivy
                    dired-launch
                    cljsbuild-mode
                    lispy
                    recentf-ext
                    diff-hl
                    fullframe
                    engine-mode
                    dired-subtree
                    shut-up
                    ))
