(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "cask")
(depends-on "use-package")
(depends-on "better-defaults")
(depends-on "dash")

;git
(depends-on "magit")
(depends-on "git-gutter-fringe+")
(depends-on "git-gutter+")

(depends-on "popwin")
(depends-on "popup")
(depends-on "popup-switcher")
(depends-on "popup-imenu")
(depends-on "flyspell-popup")
(depends-on "projectile")
(depends-on "grizzl")

(depends-on "yasnippet")

(depends-on "yaml-mode")
(depends-on "markdown-mode")
(depends-on "json-mode")
(depends-on "js2-mode")
(depends-on "css-mode")
(depends-on "sql-indent")
(depends-on "sqlup-mode")
;;(depends-on "js-mode")
;;(depends-on "emacs-lisp-mode")
(depends-on "web-mode")
(depends-on "csv-mode")
(depends-on "csv-nav")

(depends-on "diminish")
(depends-on "company")
(depends-on "company-statistics")
(depends-on "company-quickhelp")
(depends-on "thingatpt")
(depends-on "rainbow-delimiters")
(depends-on "flycheck")
(depends-on "zop-to-char")
(depends-on "imenu-anywhere")
(depends-on "dired+")
(depends-on "wdired")
(depends-on "peep-dired")
(depends-on "dired-narrow")
(depends-on "dired-rainbow")
(depends-on "ranger")
(depends-on "neotree")
(depends-on "ztree")
(depends-on "pbcopy")
(depends-on "kurecolor")
(depends-on "fancy-battery")
(depends-on "spaceline")
(depends-on "spacemacs-theme")
(depends-on "hydra")
(depends-on "ivy-hydra")
(depends-on "hungry-delete")
(depends-on "window-numbering")
(depends-on "transpose-frame")
(depends-on "highlight-numbers")
(depends-on "whitespace-cleanup-mode")
(depends-on "shrink-whitespace")
(depends-on "tidy")
(depends-on "sunshine")
(depends-on "forecast")
(depends-on "origami")
(depends-on "discover-my-major")
(depends-on "know-your-http-well")
(depends-on "with-editor")
(depends-on "visual-fill-column")
(depends-on "wgrep")
(depends-on "wgrep-ag")
(depends-on "bug-hunter")
(depends-on "calfw")
(depends-on "visible-mark")

;;org
(depends-on "org")
(depends-on "org-bullets")
(depends-on "org-journal")
(depends-on "org-plus-contrib")
(depends-on "ox-reveal")
(depends-on "org-pomodoro")
(depends-on "org-cliplink")

;;mail
(depends-on "mu4e-maildirs-extension")
(depends-on "mu4e-alert")
;;(depends-on "w3m")

;;clojure
(depends-on "clojure-mode")
(depends-on "clojure-snippets")
(depends-on "paren-face")
(depends-on "cider")
(depends-on "clj-refactor")
(depends-on "rainbow-mode")
(depends-on "highlight-parentheses")
(depends-on "paren-face")
(depends-on "clojure-cheatsheet")
(depends-on "typed-clojure-mode")
(depends-on "eval-sexp-fu")
(depends-on "cider-eval-sexp-fu")
(depends-on "4clojure")

(depends-on "flx-ido")
(depends-on "ido-vertical-mode")
(depends-on "fancy-narrow")
(depends-on "smex")
(depends-on "which-key")
(depends-on "iedit")
(depends-on "smooth-scrolling")
(depends-on "beacon")
(depends-on "super-save")
(depends-on "link-hint")
(depends-on "restclient")
(depends-on "restclient-helm")

;;(depends-on "ace-jump-buffer")
(depends-on "ace-window")
(depends-on "buffer-move")
(depends-on "undo-tree")
(depends-on "ace-jump-mode")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "wrap-region")
(depends-on "move-text")
(depends-on "hl-line+")
(depends-on "easy-kill")
(depends-on "easy-kill-extras")
(depends-on "scratch")
(depends-on "scratch-message")
(depends-on "exec-path-from-shell")
(depends-on "aggressive-indent")
(depends-on "ag")
(depends-on "anzu")
(depends-on "swiper")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "golden-ratio")
(depends-on "workgroups2")
(depends-on "ctags-update")
(depends-on "keyfreq")
(depends-on "color-identifiers-mode")
(depends-on "vlf")
(depends-on "symon")
(depends-on "typit")
(depends-on "cask-mode")
(depends-on "paradox")

;;helm
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-google")
(depends-on "helm-projectile")
(depends-on "helm-gtags")
(depends-on "helm-descbinds")
(depends-on "helm-company")
(depends-on "helm-ag")
(depends-on "helm-backup")
(depends-on "helm-mu")
(depends-on "helm-org-rifle")
;;(depends-on "helm-config")
(depends-on "helm-cider")

;;evil mode
(depends-on "evil-nerd-commenter")
(depends-on "evil-matchit")
(depends-on "evil-leader")

;;themes
(depends-on "zenburn-theme")
(depends-on "monokai-theme")

;;avy
(depends-on "avy")

;;emacs eclim
(depends-on "emacs-eclim")
(depends-on "java-imports")

(depends-on "quickrun")
(depends-on "dockerfile-mode")
(depends-on "docker")
(depends-on "xah-fly-keys")
(depends-on "key-chord")

(depends-on "embrace")
(depends-on "lispy")
(depends-on "mwim")
(depends-on "bind-key")
(depends-on "worf")
(depends-on "tiny")
(depends-on "sequential-command")
(depends-on "counsel-osx-app")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "gitattributes-mode")



