;; Initialize ;;;;

;; Keep track of loading time
(defconst emacs-start-time (current-time))
(setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
(setq exec-path (append exec-path '("/usr/local/bin")))
(setq default-directory (getenv "HOME"))
(add-to-list 'load-path (expand-file-name "elisp" user-emacs-directory))
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(require 'init-platform)
(require 'use-package)
(require 'init-defaults)
(require 'init-defuns)
(require 'init-diminish)
(require 'init-helm)
(require 'init-evil)
(require 'init-whichkey)
(require 'init-yasnippet)
(require 'init-projectile)
(require 'init-ido)
(require 'init-magit)
(require 'init-fancy-narrow)
(require 'init-org-2)
(require 'init-org-bullets)
(require 'init-clojure)
(require 'init-color-theme)
(require 'init-programming)
(require 'init-expand-region)
(require 'init-undotree)
(require 'init-smartparens)
(require 'init-hl-line)
(require 'init-drag-stuff)
(require 'init-hydra)
(require 'init-nxml)
(require 'init-company)
(require 'init-avy)
(require 'init-easy-kill)
(require 'init-imenu-anywhere)
(require 'init-dired)
(require 'init-zop-to-char)
(require 'init-iedit)
(require 'init-elisp-slime-nav)
(require 'init-aggressive-indent)
(require 'init-ag)
(require 'init-anzu)
(require 'init-ivy)
(require 'init-smooth-scrolling)
(require 'init-beacon)
(require 'init-super-save)
(require 'init-link-hint)
(require 'init-flycheck)
(require 'init-git)
(require 'init-highlight-parentheses)
(require 'init-weather)
(require 'init-eval-sexp-fu)
(require 'init-ace-window)
(require 'init-transpose)
(require 'init-rainbow-mode)
(require 'init-kurecolor)
(require 'init-help)
(require 'init-sql)
(require 'init-golden-ratio)
(require 'init-neotree)
(require 'init-popwin)
(require 'init-popup)
(require 'init-keyfreq)
(require 'init-color-identifiers)
(require 'init-restclient)
(require 'init-fancy-battery)
(require 'init-window-numbering)
(require 'init-pbcopy)
(require 'init-mu4e)
(require 'init-cal)
(require 'init-spaceline)
(require 'init-workgroups2)
(require 'init-keybindings)

(let ((elapsed (float-time (time-subtract (current-time)
                                          emacs-start-time))))
  (message "Loaded packages in %.3fs" elapsed))

(let ((local-config (expand-file-name "local.el" user-emacs-directory)))
  (when (file-exists-p local-config)
    (load local-config)))

(if (daemonp)
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (select-frame frame)
                (setq ns-use-srgb-colorspace nil)
                (load-theme 'spacemacs-dark t)))
  (load-theme 'spacemacs-dark t))
